# Only kick players if tps is lower than this
Minimum_tps: 14

# Wait for a player to be idle for this long before setting them afk
# Must be more than 20 seconds
Afk_seconds: 600

# How often to check if a player is afk
Activity_check_frequency: 5

# Kick these players (list of uuids)
Kick_players: []
